// Liste des pays de naissance (source: table demarche_acte_pays)
// France/DOM-TOM = valeur vide (premier de la liste)
// IDs alignes avec la base Advercity

export interface CountryOption {
  id: number;
  label: string;
}

/** France ou DOM-TOM (valeur speciale: id=0, value='') */
export const FRANCE_OPTION: CountryOption = { id: 0, label: 'France ou DOM-TOM' };

/** Liste complete des pays (hors France) */
export const COUNTRIES: CountryOption[] = [
  { id: 1, label: 'Afghanistan' },
  { id: 2, label: 'Afrique du Sud' },
  { id: 3, label: 'Albanie' },
  { id: 4, label: 'Algérie' },
  { id: 5, label: 'Algérie période française' },
  { id: 6, label: 'Allemagne' },
  { id: 7, label: 'Andorre' },
  { id: 8, label: 'Angola' },
  { id: 9, label: 'Antigua et Barbuda' },
  { id: 10, label: 'Antilles britanniques' },
  { id: 11, label: 'Antilles néerlandaises' },
  { id: 12, label: 'Arabie Saoudite' },
  { id: 13, label: 'Argentine' },
  { id: 14, label: 'Arménie' },
  { id: 15, label: 'Australie' },
  { id: 16, label: 'Autriche' },
  { id: 17, label: 'Autriche-Hongrie' },
  { id: 18, label: 'Azerbaïdjan' },
  { id: 19, label: 'Bahamas' },
  { id: 20, label: 'Bahrein' },
  { id: 21, label: 'Bangladesh' },
  { id: 22, label: 'Barbade' },
  { id: 23, label: 'Bechuanaland' },
  { id: 24, label: 'Belau' },
  { id: 25, label: 'Belgique' },
  { id: 26, label: 'Bélize' },
  { id: 27, label: 'Bénin' },
  { id: 28, label: 'Bhoutan' },
  { id: 29, label: 'Biélorussie' },
  { id: 30, label: 'Birmanie' },
  { id: 31, label: 'Bolivie' },
  { id: 32, label: 'Bosnie-Herzégovine' },
  { id: 33, label: 'Botswana' },
  { id: 34, label: 'Brésil' },
  { id: 35, label: 'Brunei' },
  { id: 36, label: 'Bulgarie' },
  { id: 37, label: 'Burkina Faso' },
  { id: 38, label: 'Burundi' },
  { id: 39, label: 'Cambodge' },
  { id: 40, label: 'Cameroun' },
  { id: 41, label: 'Canada' },
  { id: 42, label: 'Cap-Vert' },
  { id: 43, label: 'Ceylan' },
  { id: 44, label: 'Chili' },
  { id: 45, label: 'Chine' },
  { id: 46, label: 'Chypre' },
  { id: 47, label: 'Cisjordanie' },
  { id: 48, label: 'Colombie' },
  { id: 49, label: 'Comores' },
  { id: 50, label: 'Congo' },
  { id: 51, label: 'Congo belge' },
  { id: 52, label: 'Congo-Brazzaville' },
  { id: 53, label: 'Congo-Kinshasa' },
  { id: 54, label: 'Congo-Léopoldville' },
  { id: 55, label: 'Corée' },
  { id: 56, label: 'Corée du Nord' },
  { id: 57, label: 'Corée du Sud' },
  { id: 58, label: 'Costa Rica' },
  { id: 59, label: 'Côte d\'Ivoire' },
  { id: 60, label: 'Côte de l\'Or' },
  { id: 61, label: 'Côte française des Somalis' },
  { id: 62, label: 'Croatie' },
  { id: 63, label: 'Cuba' },
  { id: 64, label: 'Dahomey' },
  { id: 65, label: 'Danemark' },
  { id: 66, label: 'Djibouti' },
  { id: 67, label: 'Dominique' },
  { id: 68, label: 'Egypte' },
  { id: 69, label: 'Emirats arabes unis' },
  { id: 70, label: 'Empire ottoman' },
  { id: 71, label: 'Equateur' },
  { id: 72, label: 'Erythrée' },
  { id: 73, label: 'Espagne' },
  { id: 74, label: 'Estonie' },
  { id: 75, label: 'Etats-Unis' },
  { id: 76, label: 'Ethiopie' },
  { id: 77, label: 'Fidji' },
  { id: 78, label: 'Finlande' },
  { id: 79, label: 'Formose' },
  { id: 80, label: 'Gabon' },
  { id: 81, label: 'Gambie' },
  { id: 82, label: 'Géorgie' },
  { id: 83, label: 'Ghana' },
  { id: 84, label: 'Grèce' },
  { id: 85, label: 'Grenade' },
  { id: 86, label: 'Guatémala' },
  { id: 87, label: 'Guinée' },
  { id: 88, label: 'Guinée équatoriale' },
  { id: 89, label: 'Guinée espagnole' },
  { id: 90, label: 'Guinée portugaise' },
  { id: 91, label: 'Guinée-Bissao' },
  { id: 92, label: 'Guyana' },
  { id: 93, label: 'Guyane britannique' },
  { id: 94, label: 'Guyane hollandaise' },
  { id: 95, label: 'Haïti' },
  { id: 96, label: 'Haute-Volta' },
  { id: 97, label: 'Honduras' },
  { id: 98, label: 'Honduras britannique' },
  { id: 99, label: 'Hong Kong' },
  { id: 100, label: 'Hongrie' },
  { id: 101, label: 'Iles Marshall' },
  { id: 102, label: 'Iles Salomon' },
  { id: 103, label: 'Inde' },
  { id: 104, label: 'Indes' },
  { id: 105, label: 'Indes anglaises' },
  { id: 106, label: 'Indes néerlandaises' },
  { id: 107, label: 'Indonésie' },
  { id: 108, label: 'Irak' },
  { id: 109, label: 'Iran' },
  { id: 110, label: 'Irlande' },
  { id: 111, label: 'Islande' },
  { id: 112, label: 'Israël' },
  { id: 113, label: 'Italie' },
  { id: 114, label: 'Jamaïque' },
  { id: 115, label: 'Japon' },
  { id: 116, label: 'Jordanie' },
  { id: 117, label: 'Kazakhstan' },
  { id: 118, label: 'Kenya' },
  { id: 119, label: 'Kirghizie' },
  { id: 120, label: 'Kirghizistan' },
  { id: 121, label: 'Kiribati' },
  { id: 122, label: 'Kosovo' },
  { id: 123, label: 'Koweït' },
  { id: 124, label: 'Laos' },
  { id: 125, label: 'Lesotho' },
  { id: 126, label: 'Lettonie' },
  { id: 127, label: 'Liban' },
  { id: 128, label: 'Libéria' },
  { id: 129, label: 'Libye' },
  { id: 130, label: 'Liechtenstein' },
  { id: 131, label: 'Lituanie' },
  { id: 132, label: 'Luxembourg' },
  { id: 133, label: 'Macao' },
  { id: 134, label: 'Macédoine' },
  { id: 135, label: 'Madagascar' },
  { id: 136, label: 'Malaisie' },
  { id: 137, label: 'Malawi' },
  { id: 138, label: 'Maldives' },
  { id: 139, label: 'Mali' },
  { id: 140, label: 'Malte' },
  { id: 141, label: 'Maroc' },
  { id: 142, label: 'Maurice' },
  { id: 143, label: 'Mauritanie' },
  { id: 144, label: 'Mexique' },
  { id: 145, label: 'Micronésie' },
  { id: 146, label: 'Moldavie' },
  { id: 147, label: 'Monaco' },
  { id: 148, label: 'Mongolie' },
  { id: 149, label: 'Monténégro' },
  { id: 150, label: 'Mozambique' },
  { id: 151, label: 'Namibie' },
  { id: 152, label: 'Nauru' },
  { id: 153, label: 'Népal' },
  { id: 154, label: 'Nicaragua' },
  { id: 155, label: 'Niger' },
  { id: 156, label: 'Nigéria' },
  { id: 157, label: 'Norvège' },
  { id: 158, label: 'Nouvelle-Zélande' },
  { id: 159, label: 'Nouvelles-Hébrides' },
  { id: 160, label: 'Nyassaland' },
  { id: 161, label: 'Oman' },
  { id: 162, label: 'Oubangui-Chari' },
  { id: 163, label: 'Ouganda' },
  { id: 164, label: 'Ouzbékistan' },
  { id: 165, label: 'Pakistan' },
  { id: 166, label: 'Pakistan oriental' },
  { id: 167, label: 'Palau' },
  { id: 168, label: 'Palestine' },
  { id: 169, label: 'Panama' },
  { id: 170, label: 'Papouasie-Nouvelle Guinée' },
  { id: 171, label: 'Paraguay' },
  { id: 172, label: 'Pays-Bas' },
  { id: 173, label: 'Pérou' },
  { id: 174, label: 'Perse' },
  { id: 175, label: 'Philippines' },
  { id: 176, label: 'Pologne' },
  { id: 177, label: 'Portugal' },
  { id: 178, label: 'Qatar' },
  { id: 179, label: 'République centrafricaine' },
  { id: 180, label: 'République démocratique allemande' },
  { id: 181, label: 'République démocratique du Congo' },
  { id: 182, label: 'République dominicaine' },
  { id: 183, label: 'République du Congo' },
  { id: 184, label: 'République fédérale d\'Allemagne' },
  { id: 185, label: 'République populaire du Congo' },
  { id: 186, label: 'République tchèque' },
  { id: 187, label: 'Rhodésie du Nord' },
  { id: 188, label: 'Rhodésie du Sud' },
  { id: 189, label: 'Roumanie' },
  { id: 190, label: 'Royaume des Serbes, Croates et Slovènes' },
  { id: 191, label: 'Royaume-Uni' },
  { id: 192, label: 'Russie' },
  { id: 193, label: 'Rwanda' },
  { id: 194, label: 'Rwanda-Urundi' },
  { id: 195, label: 'Sahara occidental' },
  { id: 196, label: 'Saint-Christophe-et-Niévès' },
  { id: 197, label: 'Saint-Marin' },
  { id: 198, label: 'Saint-Siège' },
  { id: 199, label: 'Saint-Vincent-et-les Grenadines' },
  { id: 200, label: 'Sainte-Lucie' },
  { id: 201, label: 'Salvador' },
  { id: 202, label: 'Samoa occidentales' },
  { id: 203, label: 'Sao Tomé-et-Principe' },
  { id: 204, label: 'Sénégal' },
  { id: 205, label: 'Serbie' },
  { id: 206, label: 'Serbie-et-Monténégro' },
  { id: 207, label: 'Seychelles' },
  { id: 208, label: 'Siam' },
  { id: 209, label: 'Sierra Leone' },
  { id: 210, label: 'Singapour' },
  { id: 211, label: 'Slovaquie' },
  { id: 212, label: 'Slovénie' },
  { id: 213, label: 'Somalie' },
  { id: 214, label: 'Soudan' },
  { id: 215, label: 'Soudan français' },
  { id: 216, label: 'Sri Lanka' },
  { id: 217, label: 'Suède' },
  { id: 218, label: 'Suisse' },
  { id: 219, label: 'Suriname' },
  { id: 220, label: 'Swaziland' },
  { id: 221, label: 'Syrie' },
  { id: 222, label: 'Tadjikistan' },
  { id: 223, label: 'Taiwan' },
  { id: 224, label: 'Tanganika' },
  { id: 225, label: 'Tanzanie' },
  { id: 226, label: 'Tchad' },
  { id: 227, label: 'Tchécoslovaquie' },
  { id: 228, label: 'Territoire français des Afars et des Issas' },
  { id: 229, label: 'Territoires palestiniens' },
  { id: 230, label: 'Territoires palestiniens Israël' },
  { id: 231, label: 'Territoires palestiniens Palestine' },
  { id: 232, label: 'Thaïlande' },
  { id: 233, label: 'Timor oriental' },
  { id: 234, label: 'Togo' },
  { id: 235, label: 'Tonga' },
  { id: 236, label: 'Transjordanie' },
  { id: 237, label: 'Trinité et Tobago' },
  { id: 238, label: 'Tunisie' },
  { id: 239, label: 'Turkménistan' },
  { id: 240, label: 'Turquie' },
  { id: 241, label: 'Tuvalu' },
  { id: 242, label: 'Ukraine' },
  { id: 243, label: 'Union des républiques socialistes soviétiques' },
  { id: 244, label: 'Uruguay' },
  { id: 245, label: 'Vanuatu' },
  { id: 246, label: 'Vatican' },
  { id: 247, label: 'Venezuela' },
  { id: 248, label: 'Vietnam' },
  { id: 249, label: 'Yémen' },
  { id: 250, label: 'Yémen du Nord' },
  { id: 251, label: 'Yémen du Sud' },
  { id: 252, label: 'Yougoslavie' },
  { id: 253, label: 'Zaïre' },
  { id: 254, label: 'Zambie' },
  { id: 255, label: 'Zanzibar' },
  { id: 256, label: 'Zimbabwe' },
];

/** Liste avec France en premier (pour les selects) */
export const COUNTRIES_WITH_FRANCE: CountryOption[] = [
  FRANCE_OPTION,
  ...COUNTRIES,
];

/** Trouve un pays par ID */
export function getCountryById(id: number): CountryOption | undefined {
  if (id === 0) return FRANCE_OPTION;
  return COUNTRIES.find(c => c.id === id);
}

/** Trouve un pays par label */
export function getCountryByLabel(label: string): CountryOption | undefined {
  return COUNTRIES_WITH_FRANCE.find(c => c.label.toLowerCase() === label.toLowerCase());
}
